version: 2

builds:
  - main: .
    binary: cbs
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.buildTime={{.Date}}
      - -X main.gitCommit={{.Commit}}

archives:
  - formats: [ 'binary' ]
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"